trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: HashiCorpSetup@0
  inputs:
    terraformVersion: '1.1.7'

- script: |
    cd terraform
    terraform init
  displayName: 'Terraform Init'

- script: |
    cd terraform
    terraform fmt -check
  displayName: 'Terraform Format'

- script: |
    cd terraform
    terraform validate
  displayName: 'Terraform Validate'

- script: |
    cd terraform
    terraform plan
  displayName: 'Terraform Plan'

- script: |
    cd terraform
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
